version: "3.8"
services:
    app:
        build:
            context: ./app
        ports:
            - "5000:5000"
    server:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
