openapi: 3.0.0
paths:
  /api/s2s:
    get:
      operationId: S2SController_throw
      parameters: []
      responses:
        '200':
          description: ''
    post:
      operationId: S2SController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/S2SRequestDTO'
      responses:
        '201':
          description: ''
  /users/{nsaid}:
    get:
      operationId: 取得
      summary: ''
      parameters:
        - name: nsaid
          required: true
          in: path
          description: ユーザーID
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      tags:
        - ユーザー
    put:
      operationId: 更新
      summary: ''
      parameters:
        - name: nsaid
          required: true
          in: path
          description: ユーザーID
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      tags:
        - ユーザー
    delete:
      operationId: 削除
      summary: ''
      parameters:
        - name: nsaid
          required: true
          in: path
          description: ユーザーID
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - ユーザー
  /users:
    post:
      operationId: 取得
      summary: ''
      parameters:
        - name: nsaid
          required: true
          in: path
          description: ユーザーID
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      tags:
        - ユーザー
  /results/{salmon_id}:
    get:
      operationId: 取得
      summary: ''
      parameters:
        - name: salmon_id
          required: true
          in: path
          description: リザルトID
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - リザルト
    put:
      operationId: 更新
      summary: ''
      parameters:
        - name: salmon_id
          required: true
          in: path
          description: リザルトID
          schema:
            type: integer
      responses:
        '200':
          description: ''
      tags:
        - リザルト
    delete:
      operationId: リザルト削除
      summary: ''
      parameters:
        - name: salmon_id
          required: true
          in: path
          description: リザルトID
          schema:
            type: integer
      responses:
        '200':
          description: ''
      tags:
        - リザルト
  /results/schedules/{schedule_id}:
    get:
      operationId: スケジュール指定
      summary: ''
      parameters:
        - name: schedule_id
          required: true
          in: path
          description: シフトID
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                title: PaginatedResponseOfResponse
                allOf:
                  - $ref: '#/components/schemas/PaginatedDto'
                  - properties:
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/Response'
      tags:
        - リザルト一覧
  /results/users/{nsaid}:
    get:
      operationId: プレイヤー指定
      summary: ''
      parameters:
        - name: nsaid
          required: true
          in: path
          description: プレイヤーID
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                title: PaginatedResponseOfResponse
                allOf:
                  - $ref: '#/components/schemas/PaginatedDto'
                  - properties:
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/Response'
      tags:
        - リザルト一覧
  /results:
    post:
      operationId: 登録
      summary: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - リザルト
  /ranking/schedules/{schedule_id}:
    get:
      operationId: 取得
      summary: ''
      parameters:
        - name: schedule_id
          required: true
          in: path
          description: シフトID
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Waves'
      tags:
        - ランキング
info:
  title: Salmon Stats API Documents
  description: ''
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    S2SRequestDTO:
      type: object
      properties: {}
    Response:
      type: object
      properties:
        salmon_id:
          type: integer
        boss_counts:
          type: array
          items:
            type: number
        boss_kill_counts:
          type: array
          items:
            type: number
        danger_rate:
          type: double
        start_time:
          type: integer
        end_time:
          type: integer
        play_time:
          type: integer
        schedule:
          $ref: '#/components/schemas/Schedule'
        job_results:
          $ref: '#/components/schemas/JobResult'
      required:
        - salmon_id
        - boss_counts
        - boss_kill_counts
        - danger_rate
        - start_time
        - end_time
        - play_time
        - schedule
        - job_results
    PaginatedDto:
      type: object
      properties:
        total:
          type: number
        limit:
          type: number
        offset:
          type: number
      required:
        - total
        - limit
        - offset
    Schedule:
      type: object
      properties:
        stage_id:
          type: string
          enum:
            - SHAKEUP
            - SHAKESHIP
            - SHAKEHOUSE
            - SHAKELIFT
            - SHAKERIDE
        start_time:
          type: integer
        end_time:
          type: integer
        weapon_lists:
          type: string
          enum:
            - RANDOMGOLD
            - RANDOMGREEN
            - SHOOTERSHORT
            - SHOOTERFIRST
            - SHOOTERPRECISION
            - SHOOTERBLAZE
            - SHOOTERNORMAL
            - SHOOTERGRAVITY
            - SHOOTERQUICKMIDDLE
            - SHOOTEREXPERT
            - SHOOTERHEAVY
            - SHOOTERLONG
            - SHOOTERBLASTERSHORT
            - SHOOTERBLASTERMIDDLE
            - SHOOTERBLASTERLONG
            - SHOOTERBLASTERLIGHTSHORT
            - SHOOTERBLASTERLIGHT
            - SHOOTERBLASTERLIGHTLONG
            - SHOOTERTRIPLEQUICK
            - SHOOTERTRIPLEMIDDLE
            - SHOOTERFLASH
            - ROLLERCOMPACT
            - ROLLERNORMAL
            - ROLLERHEAVY
            - ROLLERHUNTER
            - ROLLERBRUSHMINI
            - ROLLERBRUSHNORMAL
            - CHARGERQUICK
            - CHARGERNORMAL
            - CHARGERNORMALSCOPE
            - CHARGERLONG
            - CHARGERLONGSCOPE
            - CHARGERLIGHT
            - CHARGERKEEPER
            - SLOSHERSTRONG
            - SLOSHERDIFFUSION
            - SLOSHERLAUNCHER
            - SLOSHERBATHTUB
            - SLOSHERWASHTUB
            - SPINNERQUICK
            - SPINNERSTANDARD
            - SPINNERHYPER
            - SPINNERDOWNPOUR
            - SPINNERSEREIN
            - TWINSSHORT
            - TWINSNORMAL
            - TWINSGALLON
            - TWINSDUAL
            - TWINSSTEPPER
            - UMBRELLANORMAL
            - UMBRELLAWIDE
            - UMBRELLACOMPACT
            - SHOOTERBLASTERBURST
            - UMBRELLAAUTOASSAULT
            - CHARGERSPARK
            - SLOSHERVASE
      required:
        - stage_id
        - start_time
        - end_time
        - weapon_lists
    JobResult:
      type: object
      properties:
        failure_reason:
          type: string
          enum:
            - TIMELIMIT
            - WIPEOUT
          nullable: true
        failure_wave:
          type: integer
          nullable: true
        is_clear:
          type: boolean
      required:
        - failure_reason
        - failure_wave
        - is_clear
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_description:
          type: string
      required:
        - error
        - error_description
    Waves:
      type: object
      properties:
        salmon_id:
          type: integer
        event_type:
          type: string
          enum:
            - WATERLEVELS
            - RUSH
            - GEYSER
            - GRILLER
            - RALLY
            - FOG
            - MISSILE
        water_level:
          type: string
          enum:
            - LOW
            - MIDDLE
            - HIGH
        golden_ikura_num:
          type: integer
        golden_ikura_pop_num:
          type: integer
        ikura_num:
          type: integer
        quota_num:
          type: integer
      required:
        - salmon_id
        - event_type
        - water_level
        - golden_ikura_num
        - golden_ikura_pop_num
        - ikura_num
        - quota_num
