openapi: 3.0.0
paths:
  /api/s2s:
    get:
      operationId: S2SController_throw
      parameters: []
      responses:
        '200':
          description: ''
    post:
      operationId: S2SController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/S2SRequestDTO'
      responses:
        '201':
          description: ''
  /api/waves:
    post:
      operationId: WavesController_create
      parameters: []
      responses:
        '201':
          description: ''
  /api/waves/{{start_time}}:
    get:
      operationId: WavesController_find
      parameters: []
      responses:
        '200':
          description: ''
info:
  title: Salmon Stats API Documents
  description: ''
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    S2SRequestDTO:
      type: object
      properties: {}
